<template>
  <!-- Modal Backdrop -->
  <div 
    v-if="isOpen" 
    class="fixed inset-0 bg-black bg-opacity-50 z-[9999] flex items-center justify-center p-2 sm:p-4"
    @click="closeModal"
  >
    <!-- Modal Content -->
    <div 
      class="bg-white rounded-lg shadow-xl w-full max-w-7xl max-h-[95vh] overflow-hidden relative"
      @click.stop
    >
      <!-- Modal Header -->
      <div class="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-4 sm:p-6">
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div class="flex-1">
            <h2 class="text-xl sm:text-2xl font-bold">Report Details</h2>
            <p class="text-blue-100 mt-1 text-sm sm:text-base" v-if="reportData">
              {{ reportData.student?.name }} - {{ reportData.report?.term?.term_name || 'General Report' }}
            </p>
          </div>
          <div class="flex items-center space-x-2 sm:space-x-3 justify-end">
            <button
              @click="printReport"
              class="bg-white bg-opacity-20 hover:bg-opacity-30 text-white px-3 py-2 sm:px-4 sm:py-2 rounded-lg transition-colors flex items-center space-x-1 sm:space-x-2 text-sm sm:text-base"
            >
              <i class="fas fa-print text-sm"></i>
              <span class="hidden sm:inline">Print</span>
            </button>
            <button
              @click="closeModal"
              class="bg-white bg-opacity-20 hover:bg-opacity-30 text-white p-2 rounded-lg transition-colors"
            >
              <i class="fas fa-times text-sm"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Loading State -->
      <div v-if="loading" class="flex items-center justify-center py-20">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="p-6 text-center">
        <div class="text-red-500 mb-4">
          <i class="fas fa-exclamation-circle text-3xl"></i>
        </div>
        <h3 class="text-lg font-semibold text-gray-800 mb-2">Failed to Load Report</h3>
        <p class="text-gray-600 mb-4">{{ error }}</p>
        <button 
          @click="loadReportDetails"
          class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
        >
          Try Again
        </button>
      </div>

      <!-- Report Content -->
      <div v-else-if="reportData" class="overflow-y-auto" style="max-height: calc(95vh - 120px);">
        <!-- Report Header Info -->
        <div class="bg-gray-50 p-4 sm:p-6 border-b">
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4 sm:gap-6">
            <div>
              <h4 class="font-semibold text-gray-800 mb-2 text-sm sm:text-base">Student Information</h4>
              <p class="text-xs sm:text-sm text-gray-600">Name: {{ reportData.student.name }}</p>
              <p class="text-xs sm:text-sm text-gray-600">Student ID: {{ reportData.student.student_code }}</p>
              <p class="text-xs sm:text-sm text-gray-600">Class: {{ reportData.student.class }}</p>
            </div>
            <div>
              <h4 class="font-semibold text-gray-800 mb-2 text-sm sm:text-base">Report Information</h4>
              <p class="text-xs sm:text-sm text-gray-600">Generated: {{ formatDate(reportData.report.generated_at) }}</p>
              <p class="text-xs sm:text-sm text-gray-600">Term: {{ reportData.report.term?.term_name || 'N/A' }}</p>
              <p class="text-xs sm:text-sm text-gray-600" v-if="reportData.report.generated_by">
                Generated By: {{ reportData.report.generated_by.name }}
              </p>
            </div>
            <div>
              <h4 class="font-semibold text-gray-800 mb-2 text-sm sm:text-base">Overall Performance</h4>
              <p class="text-xs sm:text-sm text-gray-600">GPA: {{ formatGPA(reportData.data.current_stats.gpa) }}</p>
              <p class="text-xs sm:text-sm text-gray-600">Attendance: {{ reportData.data.current_stats.attendance.percentage }}%</p>
              <p class="text-xs sm:text-sm text-gray-600">
                Rank: {{ reportData.data.current_stats.class_rank.rank }}/{{ reportData.data.current_stats.class_rank.total }}
              </p>
            </div>
          </div>
        </div>

        <!-- Academic Summary -->
        <div class="p-4 sm:p-6">
          <h3 class="text-lg sm:text-xl font-bold text-gray-800 mb-4 sm:mb-6">Academic Summary</h3>
          
          <!-- Stats Cards -->
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 mb-6 sm:mb-8">
            <div class="bg-blue-50 border border-blue-200 rounded-lg p-3 sm:p-4">
              <div class="flex items-center">
                <div class="bg-blue-100 p-2 sm:p-3 rounded-lg">
                  <i class="fas fa-chart-line text-blue-600 text-sm sm:text-base"></i>
                </div>
                <div class="ml-3 sm:ml-4">
                  <p class="text-xl sm:text-2xl font-bold text-blue-600">{{ formatGPA(reportData.data.current_stats.gpa) }}</p>
                  <p class="text-xs sm:text-sm text-gray-600">Overall GPA</p>
                </div>
              </div>
            </div>
            
            <div class="bg-green-50 border border-green-200 rounded-lg p-3 sm:p-4">
              <div class="flex items-center">
                <div class="bg-green-100 p-2 sm:p-3 rounded-lg">
                  <i class="fas fa-calendar-check text-green-600 text-sm sm:text-base"></i>
                </div>
                <div class="ml-3 sm:ml-4">
                  <p class="text-xl sm:text-2xl font-bold text-green-600">{{ reportData.data.current_stats.attendance.percentage }}%</p>
                  <p class="text-xs sm:text-sm text-gray-600">Attendance</p>
                </div>
              </div>
            </div>
            
            <div class="bg-purple-50 border border-purple-200 rounded-lg p-4">
              <div class="flex items-center">
                <div class="bg-purple-100 p-3 rounded-lg">
                  <i class="fas fa-trophy text-purple-600"></i>
                </div>
                <div class="ml-4">
                  <p class="text-2xl font-bold text-purple-600">
                    {{ reportData.data.current_stats.class_rank.rank }}/{{ reportData.data.current_stats.class_rank.total }}
                  </p>
                  <p class="text-sm text-gray-600">Class Rank</p>
                </div>
              </div>
            </div>
            
            <div class="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
              <div class="flex items-center">
                <div class="bg-yellow-100 p-3 rounded-lg">
                  <i class="fas fa-star text-yellow-600"></i>
                </div>
                <div class="ml-4">
                  <p class="text-2xl font-bold text-yellow-600">{{ reportData.data.current_stats.credits_earned }}</p>
                  <p class="text-sm text-gray-600">Credits Earned</p>
                </div>
              </div>
            </div>
          </div>

          <!-- Tabs -->
          <div class="border-b border-gray-200 mb-4 sm:mb-6">
            <nav class="-mb-px flex space-x-4 sm:space-x-8 overflow-x-auto">
              <button
                v-for="tab in tabs"
                :key="tab.id"
                @click="activeTab = tab.id"
                :class="[
                  'py-2 px-1 border-b-2 font-medium text-xs sm:text-sm transition-colors whitespace-nowrap',
                  activeTab === tab.id
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                ]"
              >
                <i :class="tab.icon" class="mr-1 sm:mr-2 text-xs sm:text-sm"></i>
                <span class="hidden sm:inline">{{ tab.name }}</span>
                <span class="sm:hidden">{{ tab.name.split(' ')[0] }}</span>
              </button>
            </nav>
          </div>

          <!-- Tab Content -->
          <div class="tab-content">
            <!-- Grades Tab -->
            <div v-show="activeTab === 'grades'">
              <div v-if="Object.keys(reportData.data.grades_by_subject).length > 0">
                <div v-for="(grades, subjectName) in reportData.data.grades_by_subject" :key="subjectName" class="mb-6 sm:mb-8">
                  <h4 class="text-base sm:text-lg font-semibold text-gray-800 mb-3 sm:mb-4">{{ subjectName }}</h4>
                  <div class="bg-white border border-gray-200 rounded-lg overflow-hidden overflow-x-auto">
                    <table class="min-w-full">
                      <thead class="bg-gray-50">
                        <tr>
                          <th class="px-2 sm:px-4 py-2 sm:py-3 text-left text-xs font-medium text-gray-500 uppercase">Assessment</th>
                          <th class="px-2 sm:px-4 py-2 sm:py-3 text-left text-xs font-medium text-gray-500 uppercase">Score</th>
                          <th class="px-2 sm:px-4 py-2 sm:py-3 text-left text-xs font-medium text-gray-500 uppercase">Percentage</th>
                          <th class="px-2 sm:px-4 py-2 sm:py-3 text-left text-xs font-medium text-gray-500 uppercase">Grade</th>
                          <th class="px-2 sm:px-4 py-2 sm:py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                        </tr>
                      </thead>
                      <tbody class="divide-y divide-gray-200">
                        <tr v-for="grade in grades" :key="grade.id">
                          <td class="px-2 sm:px-4 py-2 sm:py-3 text-xs sm:text-sm text-gray-900">{{ formatAssessmentType(grade.assessment_type) }}</td>
                          <td class="px-2 sm:px-4 py-2 sm:py-3 text-xs sm:text-sm text-gray-900">{{ grade.score_obtained }}/{{ grade.max_score }}</td>
                          <td class="px-2 sm:px-4 py-2 sm:py-3 text-xs sm:text-sm text-gray-900">{{ calculatePercentage(grade.score_obtained, grade.max_score) }}%</td>
                          <td class="px-2 sm:px-4 py-2 sm:py-3 text-xs sm:text-sm">
                            <span :class="getGradeClass(grade.grade_letter)" class="font-semibold">
                              {{ grade.grade_letter }}
                            </span>
                          </td>
                          <td class="px-2 sm:px-4 py-2 sm:py-3 text-xs sm:text-sm text-gray-500">{{ formatDate(grade.created_at) }}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div v-else class="text-center py-8 text-gray-500">
                <i class="fas fa-clipboard-list text-4xl mb-4"></i>
                <p>No grades recorded for this period</p>
              </div>
            </div>

            <!-- Attendance Tab -->
            <div v-show="activeTab === 'attendance'">
              <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                <div class="bg-green-50 border border-green-200 rounded-lg p-4 text-center">
                  <p class="text-2xl font-bold text-green-600">{{ reportData.data.term_summary.attendance_summary.present_days }}</p>
                  <p class="text-sm text-gray-600">Present Days</p>
                </div>
                <div class="bg-yellow-50 border border-yellow-200 rounded-lg p-4 text-center">
                  <p class="text-2xl font-bold text-yellow-600">{{ reportData.data.term_summary.attendance_summary.late_days }}</p>
                  <p class="text-sm text-gray-600">Late Days</p>
                </div>
                <div class="bg-red-50 border border-red-200 rounded-lg p-4 text-center">
                  <p class="text-2xl font-bold text-red-600">{{ reportData.data.term_summary.attendance_summary.absent_days }}</p>
                  <p class="text-sm text-gray-600">Absent Days</p>
                </div>
                <div class="bg-blue-50 border border-blue-200 rounded-lg p-4 text-center">
                  <p class="text-2xl font-bold text-blue-600">{{ reportData.data.term_summary.attendance_summary.total_days }}</p>
                  <p class="text-sm text-gray-600">Total Days</p>
                </div>
              </div>

              <div v-if="reportData.data.attendance_records?.length > 0" class="bg-white border border-gray-200 rounded-lg overflow-hidden">
                <table class="min-w-full">
                  <thead class="bg-gray-50">
                    <tr>
                      <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                      <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Day</th>
                      <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                      <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Notes</th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-200">
                    <tr v-for="record in reportData.data.attendance_records.slice(0, 20)" :key="record.id">
                      <td class="px-4 py-3 text-sm text-gray-900">{{ formatDate(record.date) }}</td>
                      <td class="px-4 py-3 text-sm text-gray-900">{{ formatDay(record.date) }}</td>
                      <td class="px-4 py-3 text-sm">
                        <span :class="getAttendanceStatusClass(record.status)" class="px-2 py-1 text-xs font-medium rounded-full">
                          {{ formatStatus(record.status) }}
                        </span>
                      </td>
                      <td class="px-4 py-3 text-sm text-gray-500">{{ record.notes || '-' }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div v-else class="text-center py-8 text-gray-500">
                <i class="fas fa-calendar-times text-4xl mb-4"></i>
                <p>No attendance records found for this period</p>
              </div>
            </div>

            <!-- Achievements Tab -->
            <div v-show="activeTab === 'achievements'">
              <div v-if="reportData.data.achievements?.length > 0" class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div v-for="achievement in reportData.data.achievements" :key="achievement.id" 
                     class="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                  <div class="flex items-center space-x-3">
                    <div class="bg-yellow-100 p-2 rounded-lg">
                      <i class="fas fa-trophy text-yellow-600"></i>
                    </div>
                    <div>
                      <h4 class="font-semibold text-gray-800">{{ achievement.title }}</h4>
                      <p class="text-sm text-gray-600">{{ achievement.description }}</p>
                    </div>
                  </div>
                </div>
              </div>
              <div v-else class="text-center py-8 text-gray-500">
                <i class="fas fa-trophy text-4xl mb-4"></i>
                <p>No achievements recorded for this period</p>
              </div>
            </div>

            <!-- Summary Tab -->
            <div v-show="activeTab === 'summary'">
              <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div>
                  <h4 class="text-lg font-semibold text-gray-800 mb-4">Academic Overview</h4>
                  <div class="space-y-3">
                    <div class="flex justify-between">
                      <span class="text-gray-600">Total Subjects:</span>
                      <span class="font-semibold">{{ reportData.data.term_summary.subjects_count }}</span>
                    </div>
                    <div class="flex justify-between">
                      <span class="text-gray-600">Total Assessments:</span>
                      <span class="font-semibold">{{ reportData.data.term_summary.total_assessments }}</span>
                    </div>
                    <div class="flex justify-between">
                      <span class="text-gray-600">Average Score:</span>
                      <span class="font-semibold">{{ formatPercentage(reportData.data.term_summary.average_percentage) }}%</span>
                    </div>
                    <div class="flex justify-between">
                      <span class="text-gray-600">Credits Earned:</span>
                      <span class="font-semibold">{{ reportData.data.current_stats.credits_earned }}</span>
                    </div>
                  </div>
                </div>
                
                <div>
                  <h4 class="text-lg font-semibold text-gray-800 mb-4">Attendance Overview</h4>
                  <div class="space-y-3">
                    <div class="flex justify-between">
                      <span class="text-gray-600">Attendance Rate:</span>
                      <span class="font-semibold text-green-600">{{ reportData.data.current_stats.attendance.percentage }}%</span>
                    </div>
                    <div class="flex justify-between">
                      <span class="text-gray-600">Days Present:</span>
                      <span class="font-semibold">{{ reportData.data.current_stats.attendance.present_days }}</span>
                    </div>
                    <div class="flex justify-between">
                      <span class="text-gray-600">Total Days:</span>
                      <span class="font-semibold">{{ reportData.data.current_stats.attendance.total_days }}</span>
                    </div>
                    <div class="flex justify-between">
                      <span class="text-gray-600">Class Rank:</span>
                      <span class="font-semibold">
                        {{ reportData.data.current_stats.class_rank.rank }}/{{ reportData.data.current_stats.class_rank.total }}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue'
import { reportsAPI } from '@/api/reports'

const props = defineProps({
  isOpen: {
    type: Boolean,
    default: false
  },
  reportId: {
    type: [Number, String],
    default: null
  }
})

const emit = defineEmits(['close'])

// State
const loading = ref(false)
const error = ref('')
const reportData = ref(null)
const activeTab = ref('grades')

// Tabs configuration
const tabs = ref([
  { id: 'grades', name: 'Grades', icon: 'fas fa-graduation-cap' },
  { id: 'attendance', name: 'Attendance', icon: 'fas fa-calendar-check' },
  { id: 'achievements', name: 'Achievements', icon: 'fas fa-trophy' },
  { id: 'summary', name: 'Summary', icon: 'fas fa-chart-bar' }
])

// Watch for reportId changes
watch(() => props.reportId, (newId) => {
  if (newId && props.isOpen) {
    loadReportDetails()
  }
})

// Watch for modal open/close
watch(() => props.isOpen, (isOpen) => {
  if (isOpen && props.reportId) {
    loadReportDetails()
  } else if (!isOpen) {
    // Reset state when modal closes
    reportData.value = null
    error.value = ''
    activeTab.value = 'grades'
  }
})

// Methods
const loadReportDetails = async () => {
  try {
    loading.value = true
    error.value = ''
    reportData.value = await reportsAPI.getReportDetails(props.reportId)
  } catch (err) {
    console.error('Error loading report details:', err)
    error.value = 'Failed to load report details. Please try again.'
  } finally {
    loading.value = false
  }
}

const closeModal = () => {
  emit('close')
}

const printReport = () => {
  window.print()
}

// Utility functions
const formatDate = (date) => {
  return new Date(date).toLocaleDateString()
}

const formatDay = (date) => {
  return new Date(date).toLocaleDateString('en-US', { weekday: 'long' })
}

const formatGPA = (gpa) => {
  return Number(gpa).toFixed(2)
}

const formatPercentage = (percentage) => {
  return Number(percentage).toFixed(1)
}

const calculatePercentage = (obtained, max) => {
  return max > 0 ? Math.round((obtained / max) * 100) : 0
}

const formatAssessmentType = (type) => {
  return type.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')
}

const formatStatus = (status) => {
  return status.charAt(0).toUpperCase() + status.slice(1)
}

const getGradeClass = (grade) => {
  const gradeColors = {
    'A+': 'text-green-600',
    'A': 'text-green-600',
    'A-': 'text-green-500',
    'B+': 'text-blue-600',
    'B': 'text-blue-600',
    'B-': 'text-blue-500',
    'C+': 'text-yellow-600',
    'C': 'text-yellow-600',
    'C-': 'text-yellow-500',
    'D+': 'text-orange-600',
    'D': 'text-orange-600',
    'D-': 'text-orange-500',
    'F': 'text-red-600'
  }
  return gradeColors[grade] || 'text-gray-600'
}

const getAttendanceStatusClass = (status) => {
  const statusClasses = {
    'present': 'bg-green-100 text-green-800',
    'late': 'bg-yellow-100 text-yellow-800',
    'absent': 'bg-red-100 text-red-800',
    'excused': 'bg-gray-100 text-gray-800'
  }
  return statusClasses[status] || 'bg-gray-100 text-gray-800'
}
</script>

<style scoped>
@media print {
  .modal-header button {
    display: none;
  }
}
</style>
